- charts/radar-upload-source-connector/templates/configmap.yaml
> fix integer values being converted to scientific numbers

- charts/radar-grafana/values.yaml
- Update grafana values to enable persistence and allowUiUpdates
> Update grafana values

- base.yaml
- charts/app-config/.helmignore
- charts/app-config/Chart.yaml
- charts/app-config/templates/_helpers.tpl
- charts/app-config/templates/configmap.yaml
- charts/app-config/templates/deployment.yaml
- charts/app-config/templates/ingress.yaml
- charts/app-config/templates/service.yaml
- charts/app-config/templates/serviceaccount.yaml
- charts/app-config/templates/tests/test-connection.yaml
- charts/app-config/values.yaml
- charts/management-portal/templates/configmap.yaml
- charts/postgresql/values.yaml
- helmfile.d/10-base.yaml
> Appconfig helm chart

- charts/timescaledb/values.yaml
- Adds Postgresql config to chart values
> Add Postgresql config to chart values

- charts/app-config/templates/configmap.yaml
- charts/app-config/values.yaml
- charts/radar-gateway/templates/configmap.yaml
- charts/radar-gateway/values.yaml
Updates appconfig tag and configuration belonging to tag.
> Update appconfig service

- charts/radar-upload-connect-backend/values.yaml
- charts/radar-upload-connect-frontend/values.yaml
- charts/radar-upload-source-connector/values.yaml
- Update upload connector version
> Update upload connector version

- charts/radar-jdbc-connector/templates/configmap.yaml
- charts/radar-jdbc-connector/values.yaml
- Update JDBC connector max retries and retry backoff time for failed tasks
> Update JDBC connector sink properties

- charts/radar-jdbc-connector/templates/configmap.yaml
- charts/radar-jdbc-connector/templates/deployment.yaml
- charts/radar-jdbc-connector/values.yaml
- Update to use latest jdbc connector image
- Update sink config `connection.attempts` and `connection.backoff.ms`
> Update JDBC connector

- base.yaml
- charts/radar-grafana/values.yaml
- helmfile.d/20-grafana.yaml
- Add basic auth to the Grafana metrics endpoint
(Adding it in the current chart in the meantime because I still have to test the new chart)
> Update Grafana chart

- charts/radar-upload-connect-backend/Chart.yaml
- charts/radar-upload-connect-backend/values.yaml
- charts/radar-upload-connect-frontend/Chart.yaml
- charts/radar-upload-connect-frontend/values.yaml
- charts/radar-upload-source-connector/Chart.yaml
- charts/radar-upload-source-connector/templates/configmap.yaml
- charts/radar-upload-source-connector/templates/deployment.yaml
- charts/radar-upload-source-connector/values.yaml
Ensure that large files can be processed.
> Upload connector fixes

- charts/radar-jdbc-connector/templates/configmap.yaml
- charts/radar-jdbc-connector/templates/deployment.yaml
- charts/radar-output/values.yaml
- charts/radar-rest-sources-backend/values.yaml
- charts/radar-s3-connector/templates/deployment.yaml
- charts/radar-s3-connector/templates/secrets.yaml
Small improvements:
- Bumps radar-output-restructure and rest sources backend versions
- Adds proper health check to JDBC connector
- Fixes s3 connector secret definitions
> Misc fixes

- charts/app-config-frontend/Chart.yaml
- charts/app-config-frontend/values.yaml
- charts/app-config/Chart.yaml
- charts/app-config/templates/configmap.yaml
- charts/app-config/templates/deployment.yaml
- charts/app-config/values.yaml
app-config and app-config-frontend 0.3.2
- Bumped version
- Improved health check
- Docker image now uses user ID 101.
> Update app config

- .helmdocsignore
- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/README.md
- charts/kube-prometheus-stack/README.md.gotmpl
Signed-off-by: Keyvan <keyvan@thehyve.nl>
> Added chart documentation for kube-prometheus-stack

- README.md
- bin/keystore-init
- charts/management-portal/DOCS.md.gotmpl
- charts/management-portal/README.md
- charts/management-portal/README.md.gotmpl
- charts/management-portal/values.yaml
> Updated MP readme

- README.md
- base.yaml.gotmpl
minor typos and readme improvement
fixes some minor readability issues in readme, fix correct link
**Benefits**
improved readme
none
**Checklist**
> minor typos and links

- charts/radar-upload-connect-backend/templates/deployment.yaml
- charts/radar-upload-connect-backend/values.yaml
- etc/postgresql/values.yaml
- etc/radar-upload-postgresql/values.yaml
Fixes upload connector postgresql config.
> Fix upload connector postges

- README.md
> Fix production location in readme

- etc/base.yaml
- helmfile.d/20-fitbit.yaml
Fixes and simplifies Fitbit configuration. The change is done in a backwards-compatible way.
> Fitbit example config fixes

- README.md
Add Kubernetes cluster minimum requirements in the README
> Add Kubernetes cluster minimum requirements

- helmfile.d/00-init.yaml
- helmfile.d/10-base.yaml
- helmfile.d/10-managementportal.yaml
- helmfile.d/20-fitbit.yaml
- helmfile.d/20-ingestion.yaml
- helmfile.d/20-s3.yaml
Updating applications to fix log4shell issue, not sure if we need to update any internal applications.
> Updated applications to fix log4shell

- etc/base.yaml
- etc/base.yaml.gotmpl
- helmfile.d/10-managementportal.yaml
app-config-frontend now should receive the correct `server_name` needed for defining the ingress host.
> Fixed ingress for app-config-frontend

- README.md
Added some more upgrade instructions that were needed in our experience on upgrading on 2 different clusters.
**Benefits**
- fixes #
For redis we got the error --
```
COMBINED OUTPUT:
Error: UPGRADE FAILED: cannot patch "redis-master" with kind StatefulSet: StatefulSet.apps "redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
Deleting the statefulset fixes it.
> Upgrade 1.0.0 instructions 

- .github/environments.yaml
- .gitignore
- README.md
- bin/chart-updates
- bin/generate-secrets
- bin/init
- bin/keystore-init
- bin/util.sh
- environments.yaml.tmpl
- etc/base-secrets.yaml
- etc/base.yaml
- helmfile.d/20-grafana.yaml
I'm working on a script to automatically generate random secrets to make installation easier.
Any feedback on the idea?
> Auto generate secrets

- etc/base.yaml
- helmfile.d/10-base.yaml
Adds home page to RADAR-Kubernetes. The variables are automatically initialised based on the values of the other charts.
Pending RADAR-base/radar-helm-charts#71
> Add radar-home to helm files

- .github/ci_config/install-all.yaml
- etc/base-secrets.yaml
- etc/base.yaml
- etc/radar-grafana/values.yaml
- Updates MP aRMT default client secret to empty secret (since this is now the app default)
- Update `radar-grafana` deployment strategy to `Recreate` (new pods created are stuck in initialising because of 
- volume attaching issues)
**Benefits**
- If we update aRMT client secret to empty, less configurations will be needed (in Firebase, etc)
- Updating radar-grafana deployment strategy will just delete old pods and recreate the updated pods so the volume doesn't stay attached to the old pod 
- fixes #
> Update MP client secret and radar-grafana values

- etc/base.yaml
@mpgxvii @yatharthranjan just a heads up I'm updating apps in dev branch
> Updated chart versions

- etc/base-secrets.yaml
- etc/base.yaml
- helmfile.d/20-fitbit.yaml
- Adds `radar-oura-connector` to helm files
- Chart can be found here: https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-oura-connector
**Benefits**
- Adds the Oura connector to the stack to allow pulling of data from Oura API
- fixes #
**Checklist**
> Add Oura Kafka connector to helm files

- etc/base.yaml
Fixes the build issue in [Radar-Kubernetes](https://github.com/RADAR-base/RADAR-Kubernetes/actions/runs/8643715295/job/24414441396#step:8:1279)
> Fixed radar-push-endpoint servicemonitor

- etc/base.yaml
- Updates MP, appserver, rest-sources-backend, upload-connect-backend chart versions to get egress config fixes for pod matchlabel character limit (See https://github.com/RADAR-base/radar-helm-charts/pull/116)
**Benefits**
- Truncate postgres podselector so that it is within 63 character limit
- fixes #
**Checklist**
> Update chart versions for egress config fixes

- .github/workflows/push.yaml
- README.md
Support latest versions of Kubernetes.
> Update Kubernetes version in CI

- etc/base-secrets.yaml
- helmfile.d/20-dashboard.yaml
Two minor issues fixed discovered during deployment.
> [jdbc-connector-data-dashboard-backend] Fix database credentials

- etc/base.yaml
Updating some _chart_version tags to the latest available chart
**Benefits**
use the latest charts
-
-
- fixes #
-
**Checklist**
> Bump helm chart versions

- etc/base.yaml
> [data-dashboard-backend] Up chart version to 0.2.3

- etc/base.yaml
Up chart version of catalog-server to 0.6.2
> [catalog-server] Up chart version to 0.6.2

- etc/base.yaml
Applies a hotfix to the JDBC Connector app.
> [radar-jdbc-connector] Up chart version to 0.5.3

- etc/base.yaml
> Up chart version of data-dashboard-backend to 0.3.0

- etc/base.yaml
> [radar-fitbit-connector] Up chart version to 0.3.3

- etc/base.yaml
These chart changes are small and more on the bug fix side of things.
> Updated charts

- etc/base.yaml
> Security related chart updates

- etc/base.yaml
> Up chart version of s3-proxy to 0.4.2

- etc/base.yaml
- etc/kratos/values.yaml
- etc/kratos_ui/values.yaml
- helmfile.d/10-services.yaml
Radar self enrolment ui isn't ready to be fully integrated yet, this PR brings back the old kratos ui until the new UI is integrated.
> Bring back Kratos UI

- helmfile.d/10-services.yaml
- Fix error in radar_jdbc_connector_grafana config
**Benefits**
- fixes #
**Checklist**
> Fix radar_jdbc_connector_grafana config

- helmfile.d/10-services.yaml
- Add Oura to rest-sources-backend
**Benefits**
- fixes #
**Checklist**
> Add Oura to rest-sources-backend
