RADAR-base/RADAR-Kubernetes

.github/workflows/helm-publish.yml, .gitignore, README.md, base.yaml.gotmpl, bin/keystore-init, charts/management-portal/templates/secrets-keystore.yaml, charts/management-portal/values.yaml, environments.yaml.tmpl, helmfile.d/10-managementportal.yaml
This will publish all helm charts in master branch to GitHub pages. Subsequently, helmfile can use a repository + release instead of needing to include this repository as a directory or Git submodule.
=> Publish helmcharts

charts/radar-gateway/templates/configmap.yaml, charts/radar-gateway/values.yaml
Started from the need to enable compression, this allows for more configuration of the Gateway Kafka properties.
=> Make gateway more configurable

charts/management-portal/templates/configmap.yaml, charts/management-portal/templates/deployment.yaml
Apparently quotes were being handled properly by Kubernetes so moved the health check to a separate file.
=> Moved health check to a separate file 

charts/radar-gateway/templates/hpa.yaml, charts/radar-gateway/templates/ingress.yaml, charts/radar-gateway/values.yaml
This avoids deprecation messages (ingress) and incompatibility messages (autoscaler). Also fixes default kafka endpoint.
=> Update radar-gateway resource versions

charts/radar-fitbit-connector/templates/configmap-properties.yaml, charts/radar-fitbit-connector/values.yaml
- Increase number of Fitbit connector tasks to 5 to fix continuous `Failed to make request` errors for some users
=> Update Fitbit connector config 

charts/radar-gateway/Chart.yaml, charts/radar-gateway/templates/configmap.yaml, charts/radar-gateway/templates/deployment.yaml, charts/radar-gateway/values.yaml
~Pending https://hub.docker.com/repository/registry-1.docker.io/radarbase/radar-gateway/builds/a4779181-fd3f-47f0-8715-045191bb32db.~
Image is available on docker hub.
=> Bumped radar-gateway to 0.5.5 and improved health check

charts/catalog-server/Chart.yaml, charts/catalog-server/templates/configmap-java-config.yaml, charts/catalog-server/templates/configmap.yaml, charts/catalog-server/templates/deployment.yaml, charts/catalog-server/values.yaml
Exclude specifications with the new `specificationsExclude` property. Default persistent volume to true, to reduce the number of steps to upload new schemas and specifications.
=> Bump radar-schemas and allow excluding specifications

base.yaml, base.yaml.gotmpl, charts/management-portal/values.yaml, charts/radar-gateway/values.yaml, charts/radar-jdbc-connector/values.yaml, etc/radar-grafana/dashboards/allprojects/active.json, etc/radar-grafana/dashboards/allprojects/home.json, etc/radar-grafana/dashboards/allprojects/passive.json, etc/radar-grafana/values-6.13.0-defaults.yaml, etc/radar-grafana/values.yaml, etc/timescaledb/values.yaml, helmfile.d/10-managementportal.yaml, helmfile.d/20-grafana.yaml
Make radar-grafana much more configurable per installation.
- Load dashboards on demand in your `production.yaml.gotmpl` file by adding a sequence
```yaml
radar_grafana:
dashboards:
allprojects:
home:
json: {{ readFile "etc/radar-grafana/dashboards/allprojects/home.json" | quote }}
```
- Adds a grafana_dashboard oauth client that can be used to log in without creating additional credentials in Grafana
- Upgrades timescaledb
- Fixed postgres references
=> Modifiable grafana

.helmdocsignore, charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/README.md.gotmpl, charts/radar-gateway/values.yaml
=> Add readme for radar-gateway

.helmdocsignore, charts/cert-manager/Chart.yaml, charts/cert-manager/README.md, charts/cert-manager/README.md.gotmpl, charts/cert-manager/values.yaml
Signed-off-by: Keyvan <keyvan@thehyve.nl>
=> Added chart documentation for cert-manager

helmfile.d/20-redcap.yaml
Fix spacing issue in `20-helmfile.yaml`.
**Benefits**
Allow successful run for `helmfile sync`
None
- fixes https://github.com/RADAR-base/RADAR-Kubernetes/discussions/135#discussioncomment-1590921
The dash `-` in current helmfile removes any extra space between key and the value and causes `helmfile sync` to fail.
**Checklist**
=> Fix spacing issue in redcap helmfile

README.md
Explains the DNS requirements more explicitly. This avoids the cert-manager from failing on undefined subdomains.
=> Explicitly explain DNS requirements

helmfile.d/10-base.yaml, helmfile.d/20-fitbit.yaml, helmfile.d/20-ingestion.yaml, helmfile.d/20-s3.yaml
Brings RADAR-Kubernetes up to date with radar-helm-charts, including Log4J fixes.
=> Bring kubernetes up to date with radar-helm-charts

helmfile.d/20-fitbit.yaml
`helmfile sync --concurrency 1` deployment currently fails setting if they are not defined in helmfile.d/20-fitbit.yaml  `fitbit_api_client` `fitbit_api_secret`. 
set the values for `fitbit_api_client` `fitbit_api_secret` conditional on .Values
**Benefits**
helmfile sync works
=> fix: make fitbit-client-api/secret conditional

etc/base.yaml, helmfile.d/00-init.yaml, helmfile.d/10-base.yaml, helmfile.d/10-managementportal.yaml, helmfile.d/20-appserver.yaml, helmfile.d/20-fitbit.yaml, helmfile.d/20-grafana.yaml, helmfile.d/20-ingestion.yaml, helmfile.d/20-kafka-analysis.yaml, helmfile.d/20-redcap.yaml, helmfile.d/20-s3.yaml, helmfile.d/20-upload.yaml, helmfile.d/30-confluent-cloud.yaml, helmfile.d/30-push-endpoint.yaml, helmfile.d/99-velero.yaml
Chart versions now aren't hardcoded in helmfiles and can be changed via variables.
Also shuffled order of charts in `base.yaml` based on their helmfile order.
=> Chart versions are now configurable via variables

.github/environments.yaml, .github/install-all.yaml, .github/workflows/check-deprications.yaml, README.md
Check if RADAR-Kubernetes is compatible with specific Kubernetes versions every Monday.
Also check all of the charts during `helmfile template` CI job instead of default ones.
=> Check deprecations with CI job

helmfile.d/10-base.yaml, helmfile.d/20-fitbit.yaml, helmfile.d/20-grafana.yaml, helmfile.d/20-redcap.yaml, helmfile.d/20-s3.yaml, helmfile.d/20-upload.yaml, helmfile.d/30-push-endpoint.yaml, helmfile.d/40-realtime-dashboard.yaml, helmfile.d/99-velero.yaml
This removes a lot of `if` /`hasKey` blocks and makes the logic more robust. For example, the `hasKey $dict "key.subkey"` does not work as intended and the `and` function is not short-circuiting so the templates would still throw and exception on a double `if and (hasKey ...) (hasKey ...)` block. Note: dig syntax is
```
dig "key" "subkey" $default $dict
```
The default is only used if the key does not exist, it IS used if it is empty. In some values I've used a nested dig, a first dig to find out if the user set a custom value for the key, and otherwise a dig for an appropriate default value.
=> Replace if hasKey chains with dig

.github/workflows/push.yaml, README.md
This version released last month and by the looks of it we don't need to change anything for compatibility. 
https://kubernetes.io/blog/2023/04/11/kubernetes-v1-27-release/
They added a few interesting features that we can implement in the helm charts later.
=> Support for Kubernetes 1.27

etc/base.yaml
Fixes the CVE-2023-28432 critical vulnerability on Minio
https://cve.report/CVE-2023-28432
=> Updated Minio version

CONTRIBUTING.md, README.md, etc/base.yaml.gotmpl
This PR aims to improve docs on RADAR-Kubernetes with focus on contributors and how they can help to improve RADAR-Kubernetes.
It also tries to answer to following questions:
- How to create a simple kubernetes environment
- base.yaml vs production.yaml vs values files: What configuration goes where?
- Why do we have the individual helm scripts (i.e. 20-fitbit.yaml), are they meant to be individual modules? must they be installed in order? Does anything break if I run them out of order?
=> Improve docs

.github/workflows/check_secret_replacement.yaml, bin/generate-secrets, etc/base-secrets.yaml
When new secret placeholders are defined in _base-secrets.yaml_ the bin/generate-secrets script (that should replace secret placeholders with randomized values) is sometimes not updated accordingly. This will result in the use of the word _secret_ as a weak password.
This PR will implement a check on the occurrence of the word _secret_ in the _secrets.yaml_ file left after running the bin/generate-secrets script. If detect this will cause the action to fail with a message on which secrets to update. 
This PR also updates the _generate-secrets_ script to replace any field with value `secret` with a password.
Example output:
```
Not all 'secret' fields were replaced by bin/generate-secrets script. Please make sure to cover the following fields with a 'insert_secret' entry: …
```
=> [Github Action] Check all secrets are replaced by bin/generate-secrets

helmfile.d/20-s3.yaml
The _kafka_num_brokers_ global helmfile variable was not passed to the helm chart of radar-s3 connector. This will cause the radar-s3 connector to error out when this global variable is changed. This PR fixes that.
=> [radar-s3-connector] Pass kafka_num_brokers global variable to helm chart

etc/base.yaml
=> Up chart versions of radar-s3-connector (v0.3.4) and catalog-server (v0.6.0)

docs/ksql-server_for_data-dashboard-backend.md
This PR will correct the documentation of ksql_observations kafka topic and provide examples of the _questionnaire_response_ and _questionnaire_app_event_ topics mapped to the common data model.
=> [docs] Correct OBSERVATION_TIME field in ksql_observations readme

etc/base-secrets.yaml, etc/base.yaml
This PR will pass SMTP connection credentials to the Appserver application. When value `radar_appserver.smtp.enabled=true`, Appserver will send notifications via email alongside push notifications.
**Note**
This feature depends on a new version of Appserver that is not yet available. The version bump will happen when new app version exists.
=> [RADAR-Appserver] Enable notifications via email

etc/base.yaml
Upgrade various helm chart versions.
=> Upgrade helm charts to most recent versions

.github/workflows/push.yaml
This PR tries to export the images before k3s is being removed and then import them when k3s is installed again so there wouldn't be a need to pull images as often.
=> Export and import docker images from the cache

environments.yaml.tmpl, etc/base.yaml, mods/disable_tls.yaml
When TLS termination is handled upstream, nginx-ingress should not handle TLS terminiation
This PR will:
- Disable redirect to port 443 by the Nginx reverse proxy.
- Inactivate installation of cert-manager and cert-manager-letsencrypt
=> [nginx-ingress] Impl. option to disable TLS termination

.github/workflows/push.yaml, etc/base.yaml
Only run the full tests when the CI jobs are running on the main branch or a PR to the main branch
=> Only test on main

etc/base.yaml
This PR will up the appserver appversion. This version can make use of SMTP connection credentials to the Appserver application to send notifications via email alongside push notifications.
=> [radar-appserver] Up chart version to 0.5.0

helmfile.d/10-managementportal.yaml
At present RADAR-Kubernetes hard codes the URLs used by Ory Kratos to HTTPS protocol. This does not allow local development setup using HTTP
This PR will introduce the change so that the Ory Kratos URLs can be overridden at the helmfile level.
=> [kratos, kratos-ui] Allow config of HTTP URLs

helmfile.d/10-services.yaml
In the new _needs_ helmfile dependency mechanism, kafka-dependent services wait for readiness of kafka. However, in order to be useful kafka needs to be provisioned by catalog-server first.
This PR will make all kafka-dependent services wait for readiness of catalog-server.
=> Kafka-dependent services need catalog-server readiness

.github/ci_config/k3d-config.yaml, README.md, environments.yaml.tmpl, etc/base.yaml, helmfile.d/10-services.yaml, mods/disable_monitoring_logging.yaml, mods/fast_deploy.yaml, mods/ksql-queries/_base_observations_stream.sql, mods/ksql-queries/questionnaire_app_event_observations.sql, mods/ksql-queries/questionnaire_response_observations.sql, mods/localdev.yaml, mods/minimal.yaml, mods/minimal_kafka.yaml.gotmpl
Note! This PR targets the version/various-charts branch. The target should be updated to dev after merge of this branch.
This PR will implement various changes to helmfile that aim to facilitate local development and testing of RADAR-base. These changes include:
- Local host name set to _localhost_
- Disable Prometheus monitoring
- Disable Grafana logging
- Run Kafka with single broker/zookeeper
- Run Minio with single broker (standalone mode)
- Run many services at minimal RAM usage and disk footprint
- Increase the rate for readyState polling so that pods initiate faster (untested)
The KSQL-server transformation scripts have hard coded number of partitions in their transformer logic. This forced me to copy these 'queries' files and reduce the partition number to 1. This also is …
=> Impl. helmfile modifications for local development and testing

.github/workflows/push.yaml, etc/base.yaml, helmfile.d/10-services.yaml
Fixes the dependency error during installation
=> Bumped graylog version

helmfile.d/10-services.yaml
This PR will fix the missing serverName value for app-config. This caused the return URL to contain `localhost`.
=> Fix missing serverName value for app-config

bin/generate-secrets, etc/base-secrets.yaml
MinIO won't start if the password length is less than 9 characters.
In the development setup there was a default password for MinIO, which does not meet the requirements (at least 8 characters). With that setup Minio hangs on "Adding local minio host to 'mc' configuration. " and won't start. 
Note added by @pvannierop 
Being able to use unmodified passwords is only relevant for development deployments that run wit non-randomized passwords. Hence, this change does not affect production envrionments.
=> Fix default password for minio.

environments.yaml.tmpl, etc/base-secrets.yaml, etc/base.yaml, etc/cp-nifi/values.yaml, helmfile.d/10-services.yaml
Added support for [NiFi](https://nifi.apache.org/) deployment. 
**Benefits**
NiFi can provide the user interface to create different ETL pipelines, which can be used to process and manipulate real-time data. The current version uses the [cetic/helm-nifi](https://github.com/cetic/helm-nifi)  but we can probably be going to move to [radar-helm-charts/nifi](https://github.com/RADAR-base/radar-helm-charts/pull/302) in future. 
Though NiFi provides a UI-based ETL pipeline, it does consume a substantial amount of resources. Also, the [cetic/helm-nifi](https://github.com/cetic/helm-nifi) is not being maintained anymore so we probably would need to maintain the helm charts in some capacity or find another alternative to keep up with the new …
=> Added nifi helm charts

etc/cp-schema-registry/values.yaml, etc/hydra/values.yaml, etc/kratos-ui/values.yaml, helmfile.d/10-services.yaml
- Update nginx config and disable liveness and readiness probe temporarily since the updates containing the addition of these endpoints have not been merged and released yet
**Benefits**
- fixes #
**Checklist**
=> Fix kratos ui configs

etc/base.yaml, etc/radar-self-enrolment-ui/values.yaml, helmfile.d/10-services.yaml
This will update the helm chart versions to the latest one. It will also unify the chart name of the radar_self_enrolment_ui between different places.
=> Chart updates January 
